ci: update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,6 +10,23 @@ jobs:
     if: startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+          
+      - name: Extract TS SDK version from index.html
+        id: extract_ts_sdk_version
+        run: |
+          version=$(grep -oP '"x-sdk-version":"ts-immutable-sdk-\K[0-9]+\.[0-9]+\.[0-9]+' ./Web/index.js | head -n 1)
+
+          if [[ -z "$version" ]]; then
+            echo "Error: Version not found in index.js" >&2
+            exit 1
+          fi
+
+          version=$(echo "$version" | tr -d '\r\n')
+
+          echo "VERSION=${version}" >> "$GITHUB_ENV"
+          
       - name: Build Changelog
         id: github_release
         uses: mikepenz/release-changelog-builder-action@v3
@@ -33,6 +50,9 @@ jobs:
       - name: Create Release
         uses: mikepenz/action-gh-release@v0.2.0-a03
         with:
-            body: ${{steps.github_release.outputs.changelog}}
+            body: |
+              ${{steps.github_release.outputs.changelog}}
+
+              Game bridge built from Immutable Typescript SDK version ${{ env.VERSION }}
             
       
